"""add_chapters_table

Revision ID: fb31b1cf190d
Revises: eafbf2214fc6
Create Date: 2026-06-07 03:06:47.093135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb31b1cf190d'
down_revision: Union[str, Sequence[str], None] = 'eafbf2214fc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapters',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('generation_time', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'chapter_number', name='uq_project_chapter_number')
    )
    op.create_index(op.f('ix_chapters_project_id'), 'chapters', ['project_id'], unique=False)
    op.create_index('ix_chapters_project_status', 'chapters', ['project_id', 'status'], unique=False)
    op.create_table('team_workspace_members',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team_workspaces.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_workspace_members_team_id'), 'team_workspace_members', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_workspace_members_user_id'), 'team_workspace_members', ['user_id'], unique=False)
    op.drop_index(op.f('idx_project_chapters_project_id'), table_name='project_chapters')
    op.drop_index(op.f('idx_project_chapters_project_status'), table_name='project_chapters')
    op.drop_table('project_chapters')
    op.drop_index(op.f('idx_tags_team_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_table('ai_providers')
    op.drop_table('api_keys')
    op.drop_index(op.f('idx_project_context_chapter_id'), table_name='project_context_memories')
    op.drop_index(op.f('idx_project_context_project_id'), table_name='project_context_memories')
    op.drop_index(op.f('idx_project_context_project_type'), table_name='project_context_memories')
    op.drop_table('project_context_memories')
    op.drop_index(op.f('idx_ai_models_provider_active'), table_name='ai_models')
    op.drop_table('ai_models')
    op.drop_index(op.f('idx_project_members_project_id'), table_name='project_members')
    op.drop_index(op.f('idx_project_members_user_id'), table_name='project_members')
    op.drop_table('project_members')
    op.drop_index(op.f('idx_team_members_user_role'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_index(op.f('idx_project_versions_chapter_id'), table_name='project_versions')
    op.drop_index(op.f('idx_project_versions_project_created'), table_name='project_versions')
    op.drop_index(op.f('idx_project_versions_project_id'), table_name='project_versions')
    op.drop_table('project_versions')
    op.drop_index(op.f('idx_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_entity'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_metadata_gin'), table_name='audit_logs', postgresql_using='gin')
    op.drop_index(op.f('idx_audit_logs_project_id'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_team_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('idx_teams_owner_active'), table_name='teams', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_teams_owner_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('idx_generation_outputs_created_at'), table_name='generation_outputs')
    op.drop_index(op.f('idx_generation_outputs_raw_response_gin'), table_name='generation_outputs', postgresql_using='gin')
    op.drop_table('generation_outputs')
    op.drop_table('project_tags')
    op.drop_index(op.f('idx_attachments_chapter_id'), table_name='attachments')
    op.drop_index(op.f('idx_attachments_project_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('idx_generation_requests_parameters_gin'), table_name='generation_requests', postgresql_using='gin')
    op.drop_index(op.f('idx_generation_requests_project_history'), table_name='generation_requests')
    op.drop_index(op.f('idx_generation_requests_project_id'), table_name='generation_requests')
    op.drop_index(op.f('idx_generation_requests_queue'), table_name='generation_requests', postgresql_where="((status)::text = ANY ((ARRAY['queued'::character varying, 'running'::character varying])::text[]))")
    op.drop_index(op.f('idx_generation_requests_requested_at'), table_name='generation_requests')
    op.drop_index(op.f('idx_generation_requests_requested_by'), table_name='generation_requests')
    op.drop_index(op.f('idx_generation_requests_status'), table_name='generation_requests')
    op.drop_table('generation_requests')
    op.drop_index(op.f('idx_project_shares_project_id'), table_name='project_shares')
    op.drop_index(op.f('idx_project_shares_token_active'), table_name='project_shares', postgresql_where='(revoked_at IS NULL)')
    op.drop_table('project_shares')
    op.alter_column('audio_files', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_audio_files_project_id'), table_name='audio_files')
    op.create_index(op.f('ix_audio_files_project_id'), 'audio_files', ['project_id'], unique=False)
    op.alter_column('audio_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_audio_jobs_status_created_at'), table_name='audio_jobs')
    op.drop_index(op.f('idx_audio_jobs_user_id'), table_name='audio_jobs')
    op.create_index(op.f('ix_audio_jobs_status'), 'audio_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_audio_jobs_user_id'), 'audio_jobs', ['user_id'], unique=False)
    op.alter_column('canon_chapter', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_canon_chapter_scope'), table_name='canon_chapter')
    op.create_index(op.f('ix_canon_chapter_scope_id'), 'canon_chapter', ['scope_id'], unique=False)
    op.alter_column('canon_character', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_canon_character_personality_gin'), table_name='canon_character', postgresql_using='gin')
    op.drop_index(op.f('ix_canon_character_scope'), table_name='canon_character')
    op.create_index(op.f('ix_canon_character_scope_id'), 'canon_character', ['scope_id'], unique=False)
    op.alter_column('canon_event', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_canon_event_payload_gin'), table_name='canon_event', postgresql_using='gin')
    op.drop_index(op.f('ix_canon_event_scope'), table_name='canon_event')
    op.drop_index(op.f('ix_canon_event_scope_chapter_scene'), table_name='canon_event')
    op.drop_index(op.f('ix_canon_event_scope_t_desc'), table_name='canon_event')
    op.create_index(op.f('ix_canon_event_scope_id'), 'canon_event', ['scope_id'], unique=False)
    op.alter_column('canon_location', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_canon_location_env_tags_gin'), table_name='canon_location', postgresql_using='gin')
    op.drop_index(op.f('ix_canon_location_scope'), table_name='canon_location')
    op.create_index(op.f('ix_canon_location_scope_id'), 'canon_location', ['scope_id'], unique=False)
    op.alter_column('canon_scope', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('canon_scope_project_id_key'), 'canon_scope', type_='unique')
    op.drop_index(op.f('ix_canon_scope_project'), table_name='canon_scope')
    op.create_index(op.f('ix_canon_scope_project_id'), 'canon_scope', ['project_id'], unique=True)
    op.alter_column('character_visual_variant', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_character_visual_variant_char'), table_name='character_visual_variant')
    op.drop_index(op.f('ix_character_visual_variant_face_marks_gin'), table_name='character_visual_variant', postgresql_using='gin')
    op.drop_index(op.f('ix_character_visual_variant_ref_assets_gin'), table_name='character_visual_variant', postgresql_using='gin')
    op.create_index(op.f('ix_character_visual_variant_character_id'), 'character_visual_variant', ['character_id'], unique=False)
    op.alter_column('creature_instance', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_creature_instance_condition_gin'), table_name='creature_instance', postgresql_using='gin')
    op.drop_index(op.f('ix_creature_instance_scope'), table_name='creature_instance')
    op.create_index(op.f('ix_creature_instance_scope_id'), 'creature_instance', ['scope_id'], unique=False)
    op.alter_column('lore_asset', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_lore_asset_meta_gin'), table_name='lore_asset', postgresql_using='gin')
    op.drop_index(op.f('ix_lore_asset_scope'), table_name='lore_asset')
    op.drop_index(op.f('ix_lore_asset_scope_kind'), table_name='lore_asset')
    op.create_index(op.f('ix_lore_asset_scope_id'), 'lore_asset', ['scope_id'], unique=False)
    op.alter_column('lore_chunk', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_lore_chunk_embedding_hnsw'), table_name='lore_chunk', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_lore_chunk_entities_gin'), table_name='lore_chunk', postgresql_using='gin')
    op.drop_index(op.f('ix_lore_chunk_scope_source'), table_name='lore_chunk')
    op.create_index(op.f('ix_lore_chunk_scope_id'), 'lore_chunk', ['scope_id'], unique=False)
    op.drop_index(op.f('ix_party_slot_owner'), table_name='party_slot')
    op.create_index(op.f('ix_party_slot_owner_character_id'), 'party_slot', ['owner_character_id'], unique=False)
    op.alter_column('password_reset_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_password_reset_tokens_expires_at'), table_name='password_reset_tokens')
    op.drop_index(op.f('idx_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_index(op.f('idx_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_constraint(op.f('password_reset_tokens_token_key'), 'password_reset_tokens', type_='unique')
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.alter_column('project_context_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_project_context_entries_created_at'), table_name='project_context_entries')
    op.drop_index(op.f('idx_project_context_entries_project_id'), table_name='project_context_entries')
    op.create_index(op.f('ix_project_context_entries_project_id'), 'project_context_entries', ['project_id'], unique=False)
    op.alter_column('project_team_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_project_team_tokens_project_id'), table_name='project_team_tokens')
    op.drop_index(op.f('idx_project_team_tokens_team_id'), table_name='project_team_tokens')
    op.drop_index(op.f('idx_project_team_tokens_token'), table_name='project_team_tokens')
    op.drop_constraint(op.f('project_team_tokens_token_key'), 'project_team_tokens', type_='unique')
    op.create_index(op.f('ix_project_team_tokens_project_id'), 'project_team_tokens', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_team_tokens_team_id'), 'project_team_tokens', ['team_id'], unique=False)
    op.create_index(op.f('ix_project_team_tokens_token'), 'project_team_tokens', ['token'], unique=True)
    op.add_column('projects', sa.Column('story_bible', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('outline', sa.Text(), nullable=True))
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_projects_created_at'), table_name='projects')
    op.drop_index(op.f('idx_projects_deleted_at'), table_name='projects')
    op.drop_index(op.f('idx_projects_owner_active_updated'), table_name='projects', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_projects_owner_id'), table_name='projects')
    op.drop_index(op.f('idx_projects_owner_status'), table_name='projects', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_projects_team_active_updated'), table_name='projects', postgresql_where='((deleted_at IS NULL) AND (team_id IS NOT NULL))')
    op.drop_index(op.f('idx_projects_team_id'), table_name='projects')
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.drop_constraint(op.f('projects_team_id_fkey'), 'projects', type_='foreignkey')
    op.drop_column('projects', 'visibility')
    op.drop_column('projects', 'status')
    op.drop_column('projects', 'deleted_at')
    op.drop_column('projects', 'summary')
    op.drop_column('projects', 'team_id')
    op.drop_column('projects', 'content_type')
    op.alter_column('prompt_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('prompt_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_prompt_templates_owner'), table_name='prompt_templates')
    op.drop_index(op.f('idx_prompt_templates_team'), table_name='prompt_templates')
    op.create_index(op.f('ix_prompt_templates_owner_id'), 'prompt_templates', ['owner_id'], unique=False)
    op.create_index(op.f('ix_prompt_templates_team_id'), 'prompt_templates', ['team_id'], unique=False)
    op.drop_constraint(op.f('prompt_templates_team_id_fkey'), 'prompt_templates', type_='foreignkey')
    op.create_foreign_key(None, 'prompt_templates', 'team_workspaces', ['team_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_relationship_edge_from'), table_name='relationship_edge')
    op.drop_index(op.f('ix_relationship_edge_payload_gin'), table_name='relationship_edge', postgresql_using='gin')
    op.drop_index(op.f('ix_relationship_edge_scope'), table_name='relationship_edge')
    op.drop_index(op.f('ix_relationship_edge_to'), table_name='relationship_edge')
    op.create_index(op.f('ix_relationship_edge_scope_id'), 'relationship_edge', ['scope_id'], unique=False)
    op.alter_column('team_workspaces', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_team_workspaces_owner_id'), table_name='team_workspaces')
    op.create_index(op.f('ix_team_workspaces_owner_id'), 'team_workspaces', ['owner_id'], unique=False)
    op.alter_column('users', 'email',
               existing_type=postgresql.CITEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_users_last_login_at'), table_name='users')
    op.drop_index(op.f('idx_users_status_deleted_at'), table_name='users')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'status')
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'display_name')
    op.alter_column('visual_bible', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_visual_bible_cinematic_rules_gin'), table_name='visual_bible', postgresql_using='gin')
    op.drop_index(op.f('ix_visual_bible_creature_rules_gin'), table_name='visual_bible', postgresql_using='gin')
    op.drop_index(op.f('ix_visual_bible_palette_gin'), table_name='visual_bible', postgresql_using='gin')
    op.drop_index(op.f('ix_visual_bible_style_pack_gin'), table_name='visual_bible', postgresql_using='gin')
    op.drop_index(op.f('ix_world_state_value_gin'), table_name='world_state_kv', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_world_state_value_gin'), 'world_state_kv', ['value_json'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_visual_bible_style_pack_gin'), 'visual_bible', ['style_pack_json'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_visual_bible_palette_gin'), 'visual_bible', ['palette_json'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_visual_bible_creature_rules_gin'), 'visual_bible', ['creature_rules_json'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_visual_bible_cinematic_rules_gin'), 'visual_bible', ['cinematic_rules_json'], unique=False, postgresql_using='gin')
    op.alter_column('visual_bible', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('users', sa.Column('display_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('last_login_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_index(op.f('idx_users_status_deleted_at'), 'users', ['status', 'deleted_at'], unique=False)
    op.create_index(op.f('idx_users_last_login_at'), 'users', [sa.literal_column('last_login_at DESC')], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=postgresql.CITEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_team_workspaces_owner_id'), table_name='team_workspaces')
    op.create_index(op.f('idx_team_workspaces_owner_id'), 'team_workspaces', ['owner_id'], unique=False)
    op.alter_column('team_workspaces', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_relationship_edge_scope_id'), table_name='relationship_edge')
    op.create_index(op.f('ix_relationship_edge_to'), 'relationship_edge', ['scope_id', 'to_character_id'], unique=False)
    op.create_index(op.f('ix_relationship_edge_scope'), 'relationship_edge', ['scope_id'], unique=False)
    op.create_index(op.f('ix_relationship_edge_payload_gin'), 'relationship_edge', ['payload_json'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_relationship_edge_from'), 'relationship_edge', ['scope_id', 'from_character_id'], unique=False)
    op.drop_constraint(None, 'prompt_templates', type_='foreignkey')
    op.create_foreign_key(op.f('prompt_templates_team_id_fkey'), 'prompt_templates', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_prompt_templates_team_id'), table_name='prompt_templates')
    op.drop_index(op.f('ix_prompt_templates_owner_id'), table_name='prompt_templates')
    op.create_index(op.f('idx_prompt_templates_team'), 'prompt_templates', ['team_id'], unique=False)
    op.create_index(op.f('idx_prompt_templates_owner'), 'prompt_templates', ['owner_id'], unique=False)
    op.alter_column('prompt_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('prompt_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('projects', sa.Column('content_type', sa.VARCHAR(length=30), server_default=sa.text("'novel'::character varying"), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'draft'::character varying"), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('visibility', sa.VARCHAR(length=20), server_default=sa.text("'private'::character varying"), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('projects_team_id_fkey'), 'projects', 'teams', ['team_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.create_index(op.f('idx_projects_team_id'), 'projects', ['team_id'], unique=False)
    op.create_index(op.f('idx_projects_team_active_updated'), 'projects', ['team_id', sa.literal_column('updated_at DESC')], unique=False, postgresql_where='((deleted_at IS NULL) AND (team_id IS NOT NULL))')
    op.create_index(op.f('idx_projects_owner_status'), 'projects', ['owner_id', 'status'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_index(op.f('idx_projects_owner_active_updated'), 'projects', ['owner_id', sa.literal_column('updated_at DESC')], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_projects_deleted_at'), 'projects', ['deleted_at'], unique=False)
    op.create_index(op.f('idx_projects_created_at'), 'projects', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('projects', 'outline')
    op.drop_column('projects', 'story_bible')
    op.drop_index(op.f('ix_project_team_tokens_token'), table_name='project_team_tokens')
    op.drop_index(op.f('ix_project_team_tokens_team_id'), table_name='project_team_tokens')
    op.drop_index(op.f('ix_project_team_tokens_project_id'), table_name='project_team_tokens')
    op.create_unique_constraint(op.f('project_team_tokens_token_key'), 'project_team_tokens', ['token'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_project_team_tokens_token'), 'project_team_tokens', ['token'], unique=False)
    op.create_index(op.f('idx_project_team_tokens_team_id'), 'project_team_tokens', ['team_id'], unique=False)
    op.create_index(op.f('idx_project_team_tokens_project_id'), 'project_team_tokens', ['project_id'], unique=False)
    op.alter_column('project_team_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_project_context_entries_project_id'), table_name='project_context_entries')
    op.create_index(op.f('idx_project_context_entries_project_id'), 'project_context_entries', ['project_id'], unique=False)
    op.create_index(op.f('idx_project_context_entries_created_at'), 'project_context_entries', ['project_id', sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('project_context_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.create_unique_constraint(op.f('password_reset_tokens_token_key'), 'password_reset_tokens', ['token'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_index(op.f('idx_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=False)
    op.create_index(op.f('idx_password_reset_tokens_expires_at'), 'password_reset_tokens', ['expires_at'], unique=False)
    op.alter_column('password_reset_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_party_slot_owner_character_id'), table_name='party_slot')
    op.create_index(op.f('ix_party_slot_owner'), 'party_slot', ['owner_character_id'], unique=False)
    op.drop_index(op.f('ix_lore_chunk_scope_id'), table_name='lore_chunk')
    op.create_index(op.f('ix_lore_chunk_scope_source'), 'lore_chunk', ['scope_id', 'source', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_lore_chunk_entities_gin'), 'lore_chunk', ['entity_ids'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_lore_chunk_embedding_hnsw'), 'lore_chunk', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('lore_chunk', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_lore_asset_scope_id'), table_name='lore_asset')
    op.create_index(op.f('ix_lore_asset_scope_kind'), 'lore_asset', ['scope_id', 'kind'], unique=False)
    op.create_index(op.f('ix_lore_asset_scope'), 'lore_asset', ['scope_id'], unique=False)
    op.create_index(op.f('ix_lore_asset_meta_gin'), 'lore_asset', ['meta_json'], unique=False, postgresql_using='gin')
    op.alter_column('lore_asset', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_creature_instance_scope_id'), table_name='creature_instance')
    op.create_index(op.f('ix_creature_instance_scope'), 'creature_instance', ['scope_id'], unique=False)
    op.create_index(op.f('ix_creature_instance_condition_gin'), 'creature_instance', ['condition_json'], unique=False, postgresql_using='gin')
    op.alter_column('creature_instance', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_character_visual_variant_character_id'), table_name='character_visual_variant')
    op.create_index(op.f('ix_character_visual_variant_ref_assets_gin'), 'character_visual_variant', ['ref_asset_ids'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_character_visual_variant_face_marks_gin'), 'character_visual_variant', ['face_marks_json'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_character_visual_variant_char'), 'character_visual_variant', ['character_id'], unique=False)
    op.alter_column('character_visual_variant', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_canon_scope_project_id'), table_name='canon_scope')
    op.create_index(op.f('ix_canon_scope_project'), 'canon_scope', ['project_id'], unique=False)
    op.create_unique_constraint(op.f('canon_scope_project_id_key'), 'canon_scope', ['project_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('canon_scope', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_canon_location_scope_id'), table_name='canon_location')
    op.create_index(op.f('ix_canon_location_scope'), 'canon_location', ['scope_id'], unique=False)
    op.create_index(op.f('ix_canon_location_env_tags_gin'), 'canon_location', ['env_style_tags'], unique=False, postgresql_using='gin')
    op.alter_column('canon_location', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_canon_event_scope_id'), table_name='canon_event')
    op.create_index(op.f('ix_canon_event_scope_t_desc'), 'canon_event', ['scope_id', sa.literal_column('t_index DESC')], unique=False)
    op.create_index(op.f('ix_canon_event_scope_chapter_scene'), 'canon_event', ['scope_id', 'chapter_no', 'scene_no'], unique=False)
    op.create_index(op.f('ix_canon_event_scope'), 'canon_event', ['scope_id'], unique=False)
    op.create_index(op.f('ix_canon_event_payload_gin'), 'canon_event', ['payload_json'], unique=False, postgresql_using='gin')
    op.alter_column('canon_event', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_canon_character_scope_id'), table_name='canon_character')
    op.create_index(op.f('ix_canon_character_scope'), 'canon_character', ['scope_id'], unique=False)
    op.create_index(op.f('ix_canon_character_personality_gin'), 'canon_character', ['personality_json'], unique=False, postgresql_using='gin')
    op.alter_column('canon_character', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_canon_chapter_scope_id'), table_name='canon_chapter')
    op.create_index(op.f('ix_canon_chapter_scope'), 'canon_chapter', ['scope_id'], unique=False)
    op.alter_column('canon_chapter', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_audio_jobs_user_id'), table_name='audio_jobs')
    op.drop_index(op.f('ix_audio_jobs_status'), table_name='audio_jobs')
    op.create_index(op.f('idx_audio_jobs_user_id'), 'audio_jobs', ['user_id'], unique=False)
    op.create_index(op.f('idx_audio_jobs_status_created_at'), 'audio_jobs', ['status', sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('audio_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_audio_files_project_id'), table_name='audio_files')
    op.create_index(op.f('idx_audio_files_project_id'), 'audio_files', ['project_id'], unique=False)
    op.alter_column('audio_files', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_table('project_shares',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('permission', sa.VARCHAR(length=20), server_default=sa.text("'read'::character varying"), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("permission::text = ANY (ARRAY['read'::character varying, 'comment'::character varying, 'edit'::character varying]::text[])", name=op.f('project_shares_permission_check')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('project_shares_created_by_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('project_shares_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('project_shares_pkey')),
    sa.UniqueConstraint('token', name=op.f('project_shares_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_project_shares_token_active'), 'project_shares', ['token'], unique=False, postgresql_where='(revoked_at IS NULL)')
    op.create_index(op.f('idx_project_shares_project_id'), 'project_shares', ['project_id'], unique=False)
    op.create_table('generation_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chapter_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('requested_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('template_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('model_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('prompt_input', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'queued'::character varying"), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('requested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("status::text = ANY (ARRAY['queued'::character varying, 'running'::character varying, 'succeeded'::character varying, 'failed'::character varying, 'cancelled'::character varying]::text[])", name=op.f('generation_requests_status_check')),
    sa.ForeignKeyConstraint(['chapter_id'], ['project_chapters.id'], name=op.f('generation_requests_chapter_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id'], ['ai_models.id'], name=op.f('generation_requests_model_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('generation_requests_project_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('generation_requests_requested_by_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_id'], ['prompt_templates.id'], name=op.f('generation_requests_template_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('generation_requests_pkey'))
    )
    op.create_index(op.f('idx_generation_requests_status'), 'generation_requests', ['status'], unique=False)
    op.create_index(op.f('idx_generation_requests_requested_by'), 'generation_requests', ['requested_by'], unique=False)
    op.create_index(op.f('idx_generation_requests_requested_at'), 'generation_requests', [sa.literal_column('requested_at DESC')], unique=False)
    op.create_index(op.f('idx_generation_requests_queue'), 'generation_requests', ['status', 'requested_at'], unique=False, postgresql_where="((status)::text = ANY ((ARRAY['queued'::character varying, 'running'::character varying])::text[]))")
    op.create_index(op.f('idx_generation_requests_project_id'), 'generation_requests', ['project_id'], unique=False)
    op.create_index(op.f('idx_generation_requests_project_history'), 'generation_requests', ['project_id', sa.literal_column('requested_at DESC')], unique=False)
    op.create_index(op.f('idx_generation_requests_parameters_gin'), 'generation_requests', ['parameters'], unique=False, postgresql_using='gin')
    op.create_table('attachments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chapter_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('version_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('uploaded_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('storage_provider', sa.VARCHAR(length=30), server_default=sa.text("'supabase'::character varying"), autoincrement=False, nullable=False),
    sa.Column('storage_path', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checksum_sha256', sa.CHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("storage_provider::text = ANY (ARRAY['supabase'::character varying, 's3'::character varying, 'local'::character varying, 'other'::character varying]::text[])", name=op.f('attachments_storage_provider_check')),
    sa.CheckConstraint('file_size >= 0', name=op.f('attachments_file_size_check')),
    sa.ForeignKeyConstraint(['chapter_id'], ['project_chapters.id'], name=op.f('attachments_chapter_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('attachments_project_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('attachments_uploaded_by_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['version_id'], ['project_versions.id'], name=op.f('attachments_version_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('attachments_pkey'))
    )
    op.create_index(op.f('idx_attachments_project_id'), 'attachments', ['project_id'], unique=False)
    op.create_index(op.f('idx_attachments_chapter_id'), 'attachments', ['chapter_id'], unique=False)
    op.create_table('project_tags',
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('project_tags_project_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('project_tags_tag_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'tag_id', name=op.f('project_tags_pkey'))
    )
    op.create_table('generation_outputs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('output_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('token_usage_input', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('token_usage_output', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('latency_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('latency_ms >= 0', name=op.f('generation_outputs_latency_ms_check')),
    sa.CheckConstraint('token_usage_input >= 0', name=op.f('generation_outputs_token_usage_input_check')),
    sa.CheckConstraint('token_usage_output >= 0', name=op.f('generation_outputs_token_usage_output_check')),
    sa.ForeignKeyConstraint(['request_id'], ['generation_requests.id'], name=op.f('generation_outputs_request_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('generation_outputs_pkey')),
    sa.UniqueConstraint('request_id', name=op.f('generation_outputs_request_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_generation_outputs_raw_response_gin'), 'generation_outputs', ['raw_response'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_generation_outputs_created_at'), 'generation_outputs', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=140), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('teams_owner_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('teams_pkey')),
    sa.UniqueConstraint('slug', name=op.f('teams_slug_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_teams_owner_id'), 'teams', ['owner_id'], unique=False)
    op.create_index(op.f('idx_teams_owner_active'), 'teams', ['owner_id', sa.literal_column('created_at DESC')], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('actor_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('audit_logs_actor_user_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('audit_logs_project_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('audit_logs_team_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey'))
    )
    op.create_index(op.f('idx_audit_logs_team_id'), 'audit_logs', ['team_id'], unique=False)
    op.create_index(op.f('idx_audit_logs_project_id'), 'audit_logs', ['project_id'], unique=False)
    op.create_index(op.f('idx_audit_logs_metadata_gin'), 'audit_logs', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_audit_logs_entity'), 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('idx_audit_logs_created_at'), 'audit_logs', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_table('project_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chapter_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('version_no', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=20), server_default=sa.text("'ai'::character varying"), autoincrement=False, nullable=False),
    sa.Column('prompt', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('change_note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("source::text = ANY (ARRAY['ai'::character varying, 'manual'::character varying, 'import'::character varying]::text[])", name=op.f('project_versions_source_check')),
    sa.CheckConstraint('version_no > 0', name=op.f('project_versions_version_no_check')),
    sa.ForeignKeyConstraint(['chapter_id'], ['project_chapters.id'], name=op.f('project_versions_chapter_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('project_versions_created_by_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('project_versions_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('project_versions_pkey')),
    sa.UniqueConstraint('project_id', 'version_no', name=op.f('project_versions_project_id_version_no_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_project_versions_project_id'), 'project_versions', ['project_id'], unique=False)
    op.create_index(op.f('idx_project_versions_project_created'), 'project_versions', ['project_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_project_versions_chapter_id'), 'project_versions', ['chapter_id'], unique=False)
    op.create_table('team_members',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), server_default=sa.text("'member'::character varying"), autoincrement=False, nullable=False),
    sa.Column('invited_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('joined_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("role::text = ANY (ARRAY['owner'::character varying, 'admin'::character varying, 'editor'::character varying, 'viewer'::character varying]::text[])", name=op.f('team_members_role_check')),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], name=op.f('team_members_invited_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('team_members_team_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('team_members_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('team_members_pkey')),
    sa.UniqueConstraint('team_id', 'user_id', name=op.f('team_members_team_id_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_team_members_user_role'), 'team_members', ['user_id', 'role'], unique=False)
    op.create_table('project_members',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), server_default=sa.text("'viewer'::character varying"), autoincrement=False, nullable=False),
    sa.Column('added_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("role::text = ANY (ARRAY['owner'::character varying, 'editor'::character varying, 'viewer'::character varying]::text[])", name=op.f('project_members_role_check')),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], name=op.f('project_members_added_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('project_members_project_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('project_members_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('project_members_pkey')),
    sa.UniqueConstraint('project_id', 'user_id', name=op.f('project_members_project_id_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_project_members_user_id'), 'project_members', ['user_id'], unique=False)
    op.create_index(op.f('idx_project_members_project_id'), 'project_members', ['project_id'], unique=False)
    op.create_table('ai_models',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('provider_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('model_key', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('model_type', sa.VARCHAR(length=30), server_default=sa.text("'text_generation'::character varying"), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("model_type::text = ANY (ARRAY['text_generation'::character varying, 'chat'::character varying, 'embedding'::character varying, 'other'::character varying]::text[])", name=op.f('ai_models_model_type_check')),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_providers.id'], name=op.f('ai_models_provider_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_models_pkey')),
    sa.UniqueConstraint('provider_id', 'model_key', name=op.f('ai_models_provider_id_model_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_ai_models_provider_active'), 'ai_models', ['provider_id', 'is_active'], unique=False)
    op.create_table('project_context_memories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chapter_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('memory_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('importance', sa.SMALLINT(), server_default=sa.text('3'), autoincrement=False, nullable=False),
    sa.Column('source_version_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("memory_type::text = ANY (ARRAY['character'::character varying, 'plot'::character varying, 'world'::character varying, 'style'::character varying, 'fact'::character varying, 'other'::character varying]::text[])", name=op.f('project_context_memories_memory_type_check')),
    sa.CheckConstraint('importance >= 1 AND importance <= 5', name=op.f('project_context_memories_importance_check')),
    sa.ForeignKeyConstraint(['chapter_id'], ['project_chapters.id'], name=op.f('project_context_memories_chapter_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('project_context_memories_created_by_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('project_context_memories_project_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_version_id'], ['project_versions.id'], name=op.f('project_context_memories_source_version_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('project_context_memories_pkey')),
    sa.UniqueConstraint('project_id', 'memory_type', 'key', name=op.f('project_context_memories_project_id_memory_type_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_project_context_project_type'), 'project_context_memories', ['project_id', 'memory_type'], unique=False)
    op.create_index(op.f('idx_project_context_project_id'), 'project_context_memories', ['project_id'], unique=False)
    op.create_index(op.f('idx_project_context_chapter_id'), 'project_context_memories', ['chapter_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('key_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('key_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('last4', sa.CHAR(length=4), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('api_keys_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('api_keys_pkey')),
    sa.UniqueConstraint('user_id', 'provider', 'key_name', name=op.f('api_keys_user_id_provider_key_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('ai_providers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('base_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_providers_pkey')),
    sa.UniqueConstraint('code', name=op.f('ai_providers_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('tags',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('tags_created_by_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('tags_team_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('tags_pkey')),
    sa.UniqueConstraint('team_id', 'name', name=op.f('tags_team_id_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_tags_team_name'), 'tags', ['team_id', 'name'], unique=False)
    op.create_table('project_chapters',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chapter_no', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'draft'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("status::text = ANY (ARRAY['draft'::character varying, 'review'::character varying, 'published'::character varying, 'archived'::character varying]::text[])", name=op.f('project_chapters_status_check')),
    sa.CheckConstraint('chapter_no > 0', name=op.f('project_chapters_chapter_no_check')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('project_chapters_created_by_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('project_chapters_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('project_chapters_pkey')),
    sa.UniqueConstraint('project_id', 'chapter_no', name=op.f('project_chapters_project_id_chapter_no_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_project_chapters_project_status'), 'project_chapters', ['project_id', 'status'], unique=False)
    op.create_index(op.f('idx_project_chapters_project_id'), 'project_chapters', ['project_id'], unique=False)
    op.drop_index(op.f('ix_team_workspace_members_user_id'), table_name='team_workspace_members')
    op.drop_index(op.f('ix_team_workspace_members_team_id'), table_name='team_workspace_members')
    op.drop_table('team_workspace_members')
    op.drop_index('ix_chapters_project_status', table_name='chapters')
    op.drop_index(op.f('ix_chapters_project_id'), table_name='chapters')
    op.drop_table('chapters')
    # ### end Alembic commands ###
